---
- name: Install Java OpenJDK {{OPENJDK_VERSION}} and some basic dependencies
  yum: 
    name: unzip,java-{{OPENJDK_VERSION}}-openjdk,libselinux-python,libsemanage-python
    state: latest
  async: 250
  poll: 10

- name: Download JBoss from jboss.org
  get_url: 
    url: http://download.jboss.org/jbossas/7.1/jboss-as-{{JBOSS_AS_RELEASE}}/jboss-as-{{JBOSS_AS_RELEASE}}.zip 
    dest: /opt/jboss-as-{{JBOSS_AS_RELEASE}}.zip
  async: 250
  poll: 10

- name: Extract archive
  unarchive: 
    dest: /usr/share 
    src: /opt/jboss-as-{{JBOSS_AS_RELEASE}}.zip 
    copy: no 
    creates: /usr/share/jboss-as-{{JBOSS_AS_RELEASE}}

- name: Add group "jboss"
  group: 
    name: jboss

- name: Add user "jboss"
  user: 
    name: jboss 
    group: jboss 
    home: /home/jboss-as
    #home: /usr/share/jboss-as-{{JBOSS_AS_RELEASE}}

- name: Change ownership of JBoss installation
  file: 
    path: /usr/share/jboss-as-{{JBOSS_AS_RELEASE}}
    owner: jboss 
    group: jboss 
    state: directory 
    recurse: yes

- name: symbolically link install directory to avoid encoding the version in the init script
  file:
    src: /usr/share/jboss-as-{{JBOSS_AS_RELEASE}}
    dest: /usr/share/jboss-as
    owner: jboss
    group: jboss
    state: link

- name: Download updated jboss-modules.jar to fix null pointer exception error
  get_url: 
    url: http://repo1.maven.org/maven2/org/jboss/modules/jboss-modules/1.1.5.GA/jboss-modules-1.1.5.GA.jar
    dest: /usr/share/jboss-as-{{JBOSS_AS_RELEASE}}/jboss-modules.jar
    force: yes
    backup: yes

- name: Installing  standalone.xml Template configuration file
  template: 
    src: standalone.xml 
    dest: /usr/share/jboss-as/standalone/configuration/
    owner: jboss
    group: jboss

- name: Reset SELINUX Context of /usr/share/jboss-as-{{JBOSS_AS_RELEASE}} and /usr/share/jboss-as
  command: restorecon -RF /usr/share/jboss-as-{{JBOSS_AS_RELEASE}} /usr/share/jboss-as

- name: RHEL6- Perform Specific Configurations
  block:
    - name: RHEL6- Copy the init script
      copy: 
        src: jboss-as-standalone.sh 
        dest: /etc/init.d/jboss 
        mode: 0755

    - name: RHEL6- Fix SELINUX Contexts /etc/init.d/jboss
      command: restorecon -RF /etc/init.d/jboss

    - name: RHEL6- deploy iptables rules
      template: 
        src: iptables-save 
        dest: /etc/sysconfig/iptables

    - name: restart iptables
      service:
        name: iptables
        state: restarted
  when: ansible_distribution_major_version < "7" 

- name: RHEL7+ Perform Specific Configurations
  block:
    - name: RHEL7+ Fix the JBoss user in script
      copy: 
        src: jboss-as-standalone.sh 
        dest: /usr/share/jboss-as/bin/init.d/jboss-as-standalone.sh
        mode: 0755
        
    - name: RHEL7+ Configure the init script for systemd
      template: 
        src: jboss.systemd
        dest: /etc/systemd/system/jboss.service

    - name: RHEL7+ Fix SELINUX Contexts /etc/systemd/system/jboss.service
      command: restorecon -RF /etc/systemd/system/jboss.service
   
    - name: RHEL7+ Fix jboss-as.conf issues - create /etc/jboss-as
      file: 
        dest: /etc/jboss-as
        owner: jboss
        group: jboss
        state: directory

    - name: RHEL7+ Fix jboss-as.conf issues - link /etc/jboss-as/jboss-as.conf
      file:
        src: /usr/share/jboss-as/bin/init.d/jboss-as.conf
        dest: /etc/jboss-as/jboss-as.conf
        owner: jboss
        group: jboss
        state: link

    - name: RHEL7+ Ensure that firewalld is installed
      yum: 
        name: firewalld 
        state: present

    - name: RHEL7+ Ensure that firewalld is started
      service: 
        name: firewalld 
        state: restarted
        enabled: yes

    - name: RHEL7+ deploy firewalld rules
      firewalld: 
        immediate: no 
        port: "{{ item }}" 
        state: enabled 
        permanent: yes
      with_items:
        - "{{ http_port }}/tcp"
        - "{{ https_port }}/tcp"

    - name: RHEL7+ restart firewalld
      service: 
        name: firewalld 
        state: restarted
        enabled: yes

  when: ansible_distribution_major_version >= "7"

- name: Enable and Stop JBoss with service module
  service:
    name: jboss 
    enabled: yes 
    state: stopped

- name: Enable and Start JBoss with service module
  service:
    name: jboss 
    enabled: yes 
    state: started

- name: wait for jboss to restart
  wait_for:
    port: "{{ http_port }}"
    host: "{{ inventory_hostname }}"
    state: started
    delay: 30
    timeout: 120
  become: false
  delegate_to: localhost
  async: 250
  poll: 10
  register: wait_for_result

- name: Use URI module to Validate JBOSS Service is running
  uri:
    url: "http://{{ ansible_ssh_host }}:{{ http_port }}"
    return_content: yes
  register: webpage

- name: Fail if "Your JBoss Application Server 7 is running" is not in the output
  fail:
  when: "'Your JBoss Application Server 7 is running' not in webpage.content"
...
