---
#
# Test to Verify Hello World Test #1
#

- name: Hello World - Test 1
  my_uri:
    url: "http://{{ ansible_ssh_host }}:{{ http_port }}/helloworld/HelloWorld"
    return_content: yes
  register: hwtest1page

- name: Hello World - Validation 1
  fail:
  when: "'Hello World!' not in hwtest1page.content"

#
# Test to Verify ticket-monster Test #1
#
- name: Ticket Monster - Test 1
  my_uri:
    url: "http://{{ ansible_ssh_host }}:{{ http_port }}/ticket-monster"
    return_content: yes
  register: webpage
  ignore_errors: yes
  tags: tmtest1

- name: display test1 uri return code
  debug: 
    var: webpage.status
  tags: tmtest1

- name: Ticket Monster - Validation 1
  fail:
  when: "'Ticket Monster' not in webpage.content"
  tags: tmtest1

#
# Test to Verify ticket-monster Test #2
#
    #url: "http://{{ ansible_ssh_host }}:{{ http_port }}/ticket-monster/#/events"
- name: Ticket Monster - Test #2
  my_uri:
    url: "http://{{ ansible_ssh_host }}:{{ http_port }}/ticket-monster/rest/events"
    return_content: yes
  register: webpage
  ignore_errors: yes
  tags: tmtest2

- name: display test2 uri return code
  debug: 
    var: webpage.status
  tags: tmtest2

- name: Ticket Monster - Validation 2
  assert:
    that: 
      - "'Concert' in webpage.content"
      - "'Theatre' in webpage.content"
      - "'Sporting' in webpage.content"
  tags: tmtest2

#
# Test to Verify ticket-monster Test #3
#
   # url: "http://{{ ansible_ssh_host }}:{{ http_port }}/ticket-monster/#venues"
- name: Ticket Monster - Test 3
  my_uri:
    url: "http://{{ ansible_ssh_host }}:{{ http_port }}/ticket-monster/rest/venues"
    return_content: yes
  register: webpage
  ignore_errors: yes
  tags: tmtest3

- name: Ticket Monster - Validation 3
  fail:
  when: "'Boston' not in webpage.content"
  tags: tmtest3

#
# Test to Verify ticket-monster Test #4
#
- name: Ticket Monster - Test 4
  my_uri:
    url: "http://{{ ansible_ssh_host }}:{{ http_port }}/ticket-monster/rest/bookings/count"
    return_content: yes
    follow_redirects: yes
  register: webpage
  ignore_errors: yes
  tags: tmtest4

- name: display count value
  debug: 
    var: webpage.content
  tags: tmtest4

- name: Ticket Monster - Validation 4
  fail:
  when: "'\"count\":' not in webpage.content"
  tags: tmtest4

#
# Test to Verify ticket-monster Test #5
#
- name: Ticket Monster - Test 5
    #url: "http://{{ ansible_ssh_host }}:{{ http_port }}/ticket-monster/admin/app.html#"
  my_uri:
    url: "http://{{ ansible_ssh_host }}:{{ http_port }}/ticket-monster/admin/app.html"
    return_content: yes
    follow_redirects: yes
  register: webpage
  ignore_errors: yes
  tags: tmtest5

- name: Ticket Monster - Validation 5
  fail:
  when: "'Your application is running' not in webpage.content"
  tags: tmtest5


