- name: Create a GCP instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: "{{ my_gcp_project }}"
      gcp_cred_kind: serviceaccount
      gcp_cred_file: "{{ my_gcp_cred_file }}"
      zone: "{{ my_gcp_zone }}"
      region: "{{ my_gcp_region }}"

  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: 'ctjon-gcp-disk-instance'
         size_gb: 50
         source_image: 'rhel-6-v20190916'
         #source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk

   - name: create a network
     gcp_compute_network:
         name: 'ctjon-gcp-network-instance'
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: network

   - name: create a address
     gcp_compute_address:
         name: 'ctjon-gcp-address-instance'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address

   - name: create a instance
     gcp_compute_instance:
         state: present
         name: ctjon-jboss
         machine_type: n1-standard-1
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network: "{{ network }}"
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance

    - name: Wait for SSH to come up
      wait_for: 
        host: "{{ address.address }}"
        port: 22
        delay: 10
        timeout: 60

