---
- name: Destroy AWS Intances
  hosts: localhost
  connection: local
  gather_facts: False

  # load AWS variables from this group vars file
  vars_files:
  - group_vars/all

  tasks:
  - name: Get EC2 Instance Facts
    ec2_instance_facts:
      access_key: "{{ ec2_access_key }}"
      secret_key: "{{ ec2_secret_key }}"
      region: "{{ ec2_region }}"
      filters:
        "tag:Name": "{{tower_user_name}}_jboss_demo"
    register: ec2_result

  - name: Destroy instances
    ec2:
      access_key: "{{ ec2_access_key }}"
      secret_key: "{{ ec2_secret_key }}"
      group: "{{ ec2_security_group }}"
      type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      region: "{{ ec2_region }}"
      instance_tags: "{'ansible_group':'jboss', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'{{ tower_user_name }}''_jboss_demo'}"
      wait: true
      instance_ids: "{{ item.instance_id }}"
      state: absent
      instance_initiated_shutdown_behavior: terminate
    with_items: "{{ ec2_result.instances }}"
    async: 1000
    poll: 0

 
