---
- name: Copy hello-world application WAR file to host
  copy:
    src: jboss-helloworld.war
    dest: /var/tmp

- name: Copy ticket-monster application WAR file to host
  copy: 
    src: ticket-monster.war
    dest: /var/tmp

#- name: Deploy HelloWorld to JBoss
#  jboss:
#    deploy_path: /usr/share/jboss-as/standalone/deployments/
#    src: /var/tmp/jboss-helloworld.war 
#    deployment: helloworld.war
#    state: present
#
#- name: Use URI module to Validate Hello World Application is running
#  uri:
#    url: "http://{{ ansible_ssh_host }}:{{ http_port }}/helloworld/HelloWorld"
#    return_content: yes
#  register: webpage

#- name: Fail if "Hello World!" is not in the output
#  fail:
#  when: "'Hello World!' not in webpage.content"
  
- name: Deploy Ticket Monster to JBoss
  jboss: 
    deploy_path: /usr/share/jboss-as/standalone/deployments/
    src: /var/tmp/ticket-monster.war 
    deployment: ticket-monster.war
    state: present

- name: Use URI module to Validate Ticket Monster Application is running
  uri:
    url: "http://{{ ansible_ssh_host }}:{{ http_port }}/ticket-monster"
    return_content: yes
  register: webpage

- name: Fail if "Ticket Monster" is not in the output
  fail:
  when: "'Ticket Monster' not in webpage.content"

...
